version: '3.6'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: polling_app
      MYSQL_USER: test1
      MYSQL_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
